add lottie to verify
xFilipW/Quick-Code pull request #10
Opened 2023-10-16 16:08 UTC by xFilipW

2023-10-16 19:29 UTC, foxtrotdev requested changes

2023-10-16 19:29 UTC, foxtrotdev commented on app/src/main/res/layout/fragment_verify_success.xml
> +        android:text="@string/verify_back_to_log_in_button"
String not found!

2023-10-16 19:29 UTC, foxtrotdev commented on app/src/main/res/layout/fragment_verify_success.xml
> +        android:text="@string/verify_acc_has_been_verified"
String not found!

2023-10-16 19:29 UTC, foxtrotdev commented on app/src/main/res/layout/fragment_verify_success.xml
> +        android:text="@string/verify_congratulations"
String not found!

2023-10-16 19:29 UTC, foxtrotdev commented on app/src/main/res/layout/fragment_verify_success.xml
> +        android:text="@string/verify_congratulations"
I cannot build the project. It says that `SignupTabFragmentBinding` is missing.

2023-10-16 19:50 UTC, foxtrotdev requested changes

2023-10-16 19:50 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpTabFragment.java
>          viewModel.setListeners(v -> {
Since it has one listener, you could inline the function here.

2023-10-16 19:50 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpViewModel.java
> +    }
Since SharedPreferences starts to appear in the whole app, it it recommended to create singleton and use it for any SharedPreferences' operations.

2023-10-16 19:50 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpViewModel.java
> +        PreferenceManager.getDefaultSharedPreferences(context)
Deprecated, need to import `implementation 'androidx.preference:preference:1.2.0' or newer version.

2023-10-16 19:50 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/verifyEmail/VerifyBottomSheetDialogFragment.java
> +                                handler.post(() -> hideCircle());
Follow all lint suggestions and cleanup the code.

2023-10-16 19:50 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/verifyEmail/VerifyViewModel.java
>  import com.example.quickcode.rest.register.RegisterSuccess;
Cleanup the code.

2023-10-16 20:08 UTC, xFilipW commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpViewModel.java
> +        PreferenceManager.getDefaultSharedPreferences(context)
Should I replace it with KTX dependency?

2023-10-16 20:09 UTC, xFilipW commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpViewModel.java
> +        PreferenceManager.getDefaultSharedPreferences(context)
implementation 'androidx.preference:preference-ktx:1.2.1'

2023-10-18 07:38 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpViewModel.java
> +        PreferenceManager.getDefaultSharedPreferences(context)
No, implement the library I posted in first comment and reimport PreferenceManager to use it from androidx packagename.

2023-10-18 07:39 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/verifyEmail/VerifyBottomSheetDialogFragment.java
> +                                handler.post(() -> hideCircle());
I don't see any changes. Did you push changes?

2023-10-18 07:39 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/verifyEmail/VerifyViewModel.java
>  import com.example.quickcode.rest.register.RegisterSuccess;
I don't see any changes. Did you push changes?

2023-10-18 07:40 UTC, foxtrotdev commented on app/src/main/java/com/example/quickcode/loginRegister/SignUpTabFragment.java
>          viewModel.setListeners(v -> {
I don't see any changes. Did you push changes?

2023-10-24 18:22 UTC, closed without merging